import MenuLogo from './menu.svg';
import MoonLogo from './moon.svg';
import SunLogo from './sun.svg';
import HomeLogo from './home.svg';
import AboutLogo from './about.svg';
import UserLogo from './user.svg';
import ArticleLogo from './article.svg';
import EyeLogo from './eye.svg';
import CalendarLogo from './calendar.svg';
import GridLogo from './grid.svg';
import NotificationLogo from './notification.svg';
export {NotificationLogo, GridLogo, EyeLogo, CalendarLogo, MenuLogo, MoonLogo, SunLogo, HomeLogo, AboutLogo, UserLogo, ArticleLogo};
